// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlimpmsifpllmjglhpbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaW1wbXNpZnBsbG1qZ2xocGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Nzg2MzIsImV4cCI6MjA2NjI1NDYzMn0.cuCe08WEDajKDE87Dy2DPqiKKzZuRBynLXKGUfJ01Kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);