// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofifrgkzgixakxkrsgku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9maWZyZ2t6Z2l4YWt4a3JzZ2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODcyMjAsImV4cCI6MjA2NjE2MzIyMH0.wH7PlcdDgmkMEeQJvUaK_JV5EIFRNRGLHdAeGNRHLmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});